### ISSUE TITLE
Starting problem.

### ISSUE THREAD

**Issue by qcol** [kostasdizas/aw-watcher-sublime#1]
Thanks for that watcher. I missed it for Sublime. Unfortunately it doesn't work after installation with Package Control.

![image](https://user-images.githubusercontent.com/358993/81935368-d5cea200-95f0-11ea-9954-db3a58448ce4.png)

When I tried to preview the settings, I got a message:
![2020-05-14_14-36](https://user-images.githubusercontent.com/358993/81935575-234b0f00-95f1-11ea-8fa9-671a24416ce7.png)

**Comment by blaggacao** [comment]
Confirm, same here.

**Comment by blaggacao** [comment]
When git cloning into `.../Packages` directly, everything works. Problem seems to be with the Sublime packaging.

**Comment by kostasdizas** [comment]
Hi @qcol thanks for pointing this out. There was an issue with the settings file path, it didn't match the name of the package as it is listed on Package Control. It should be fixed now.
